/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectointegrador;

import static com.mycompany.proyectointegrador.ProyectoIntegrador.buscarProducto;
import static com.mycompany.proyectointegrador.ProyectoIntegrador.inventario;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author mil_g
 */
public class vendedor extends javax.swing.JFrame {

    /**
     * Creates new form vendedor
     */
    public vendedor() {
        initComponents();
        iniciarTabla();
        if(inventario.isEmpty()){
            testButton.setEnabled(true);
        }
    }
    
    Producto selected;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombrePeli = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        cantidadPeli = new javax.swing.JSpinner();
        precioPeli = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        eliminarField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eliminarLabel = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        eliminarAux = new javax.swing.JButton();
        eliminarDatos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        busquedaModificar = new javax.swing.JTextField();
        nombreModi = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPelis = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        cantLabel = new javax.swing.JLabel();
        cantModi = new javax.swing.JSpinner();
        precioModi = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        salirInventario = new javax.swing.JButton();
        busquedaPrincipal = new javax.swing.JTextField();
        testButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(152, 255, 150));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(208, 253, 215));
        jPanel5.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("SimSun", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 140, 74));
        jLabel1.setText("INVENTARIO");

        jTabbedPane2.setBackground(new java.awt.Color(155, 250, 176));
        jTabbedPane2.setForeground(new java.awt.Color(42, 140, 74));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(155, 250, 176));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 430));

        jLabel2.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 140, 74));
        jLabel2.setText("Nombre de la Película");

        jLabel3.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 140, 74));
        jLabel3.setText("Precio Unitario ");

        jLabel4.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 140, 74));
        jLabel4.setText("Cantidad de Unidades Disponibles");

        nombrePeli.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        nombrePeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePeliActionPerformed(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(208, 253, 215));
        agregar.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(42, 140, 74));
        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        cantidadPeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cantidadPeli.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantidadPeli.setPreferredSize(new java.awt.Dimension(80, 30));

        precioPeli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        precioPeli.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        precioPeli.setPreferredSize(new java.awt.Dimension(64, 29));
        precioPeli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioPeliFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrePeli, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(precioPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(precioPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidadPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(155, 250, 176));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel5.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 140, 74));
        jLabel5.setText("Película a Eliminar:");

        eliminarField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SimSun", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(42, 140, 74));
        jLabel6.setText("La siguiente Película será Eliminada:");

        eliminarLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        eliminarLabel.setText("---------------------------------");

        eliminar.setBackground(new java.awt.Color(208, 253, 215));
        eliminar.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        eliminar.setForeground(new java.awt.Color(42, 140, 74));
        eliminar.setText("ELIMINAR");
        eliminar.setEnabled(false);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        eliminarAux.setBackground(new java.awt.Color(208, 253, 215));
        eliminarAux.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        eliminarAux.setForeground(new java.awt.Color(42, 140, 74));
        eliminarAux.setText("BUSCAR");
        eliminarAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAuxActionPerformed(evt);
            }
        });

        eliminarDatos.setText("-------------------------------");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(eliminarDatos))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarField, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(eliminarAux)
                    .addComponent(eliminarLabel)
                    .addComponent(eliminar))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(eliminarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarAux)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(eliminarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarDatos)
                .addGap(23, 23, 23)
                .addComponent(eliminar)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(155, 250, 176));

        jLabel9.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(42, 140, 74));
        jLabel9.setText("Película a Modificar:");

        busquedaModificar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        busquedaModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaModificarKeyReleased(evt);
            }
        });

        nombreModi.setEnabled(false);
        nombreModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreModiActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(208, 253, 215));
        modificar.setFont(new java.awt.Font("SimSun", 3, 18)); // NOI18N
        modificar.setForeground(new java.awt.Color(42, 140, 74));
        modificar.setText("MODIFICAR");
        modificar.setEnabled(false);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        listaPelis.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        listaPelis.setForeground(new java.awt.Color(42, 140, 74));
        listaPelis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPelisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPelis);

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(42, 140, 74));
        jLabel8.setText("Películas en existencia");

        nameLabel.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(42, 140, 74));
        nameLabel.setText("Nombre");

        priceLabel.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(42, 140, 74));
        priceLabel.setText("Precio");

        cantLabel.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        cantLabel.setForeground(new java.awt.Color(42, 140, 74));
        cantLabel.setText("Cantidad");

        cantModi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cantModi.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        cantModi.setEnabled(false);
        cantModi.setPreferredSize(new java.awt.Dimension(80, 30));

        precioModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        precioModi.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(busquedaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modificar)
                            .addComponent(nombreModi, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel)
                            .addComponent(cantLabel)
                            .addComponent(cantModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioModi))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(busquedaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nameLabel))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nombreModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precioModi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantModi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(modificar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modificar", jPanel3);

        tablaInventario.setBackground(new java.awt.Color(155, 250, 176));
        tablaInventario.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        tablaInventario.setForeground(new java.awt.Color(42, 140, 74));
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Película", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaInventario.setPreferredSize(new java.awt.Dimension(225, 180));
        jScrollPane2.setViewportView(tablaInventario);

        salirInventario.setBackground(new java.awt.Color(155, 250, 176));
        salirInventario.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        salirInventario.setForeground(new java.awt.Color(42, 140, 74));
        salirInventario.setText("Salir");
        salirInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirInventarioActionPerformed(evt);
            }
        });

        busquedaPrincipal.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        busquedaPrincipal.setForeground(new java.awt.Color(42, 140, 74));
        busquedaPrincipal.setText("Buscar");
        busquedaPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                busquedaPrincipalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                busquedaPrincipalFocusLost(evt);
            }
        });
        busquedaPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaPrincipalKeyReleased(evt);
            }
        });

        testButton.setBackground(new java.awt.Color(155, 250, 176));
        testButton.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        testButton.setForeground(new java.awt.Color(42, 140, 74));
        testButton.setText("Test");
        testButton.setEnabled(false);
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(busquedaPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(salirInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(busquedaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(testButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salirInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePeliActionPerformed

    private void nombreModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreModiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreModiActionPerformed

    private void salirInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirInventarioActionPerformed
        // TODO add your handling code here:
        new ingreso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirInventarioActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        Number value = (Number) precioPeli.getValue();
        double precio = value.doubleValue();

        // Redondear a dos decimales usando BigDecimal
        BigDecimal bd = new BigDecimal(precio).setScale(2, RoundingMode.HALF_UP);
        precio = bd.doubleValue();
        
        if(precio<=0){
            JOptionPane.showMessageDialog(null, "Precio Inválido");
            return;
        }
        
        DefaultTableModel table = (DefaultTableModel) tablaInventario.getModel();
        
        //Guardar en inventario
        Producto aux= new Producto();
        aux.setNombre(nombrePeli.getText());
        aux.setPrecio((double)Math.floor(precio*100)/100);
        aux.setCantidad((int)cantidadPeli.getValue());
        inventario.add(aux);
        
        //Añadir a la tabla
        table.addRow(new Object[]{aux.getNombre(),aux.getPrecio(),aux.getCantidad()});
        
        //Limpiar campos
        nombrePeli.setText("");
        precioPeli.setText("");
        cantidadPeli.setValue(1);
    }//GEN-LAST:event_agregarActionPerformed

    private void busquedaPrincipalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busquedaPrincipalFocusLost
        // TODO add your handling code here:
        if(busquedaPrincipal.getText().equals("")){
            busquedaPrincipal.setText("Buscar");
        }
    }//GEN-LAST:event_busquedaPrincipalFocusLost

    private void busquedaPrincipalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busquedaPrincipalFocusGained
        // TODO add your handling code here:
        busquedaPrincipal.setText("");
    }//GEN-LAST:event_busquedaPrincipalFocusGained

    private void busquedaPrincipalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaPrincipalKeyReleased
        // TODO add your handling code here:
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tablaInventario.getModel());
            tablaInventario.setRowSorter(rowSorter);
            
            // Apply the filter based on search text
            String searchText = busquedaPrincipal.getText();  // Example search text
            RowFilter<TableModel, Object> filter = RowFilter.regexFilter(searchText, 0);  // Filter based on the first column ("Name")
            rowSorter.setRowFilter(filter);
    }//GEN-LAST:event_busquedaPrincipalKeyReleased

    private void precioPeliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioPeliFocusLost
        try {
            precioPeli.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(vendedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_precioPeliFocusLost

    private void eliminarAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAuxActionPerformed
        // TODO add your handling code here:
        try{
        Producto eliminacion=inventario.get(buscarProducto(eliminarField.getText(),inventario));
        eliminarLabel.setText(eliminacion.getNombre());
        eliminarDatos.setText("$"+eliminacion.getPrecio()+" / Cantidad: "+eliminacion.getCantidad());
        } catch (IndexOutOfBoundsException e){
            eliminarLabel.setText("Película no encontrada");
        }
        
        eliminar.setEnabled(true);
    }//GEN-LAST:event_eliminarAuxActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        inventario.remove(buscarProducto(eliminarLabel.getText(),inventario));
        DefaultTableModel modelo = (DefaultTableModel)tablaInventario.getModel();
        for(int i=0;i<modelo.getRowCount();i++){
            if(modelo.getValueAt(i, 0).equals(eliminarLabel.getText())){
                modelo.removeRow(i);
                
                //Reiniciar campos y terminar ciclo
                eliminarField.setText("");
                eliminarLabel.setText("---------------------------------");
                eliminarDatos.setText("-------------------------------");
                eliminar.setEnabled(false);
                return;
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void busquedaModificarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaModificarKeyReleased
        // TODO add your handling code here:
        DefaultListModel lista = new DefaultListModel();
        if(busquedaModificar.getText().equals("")){
            listaPelis.setModel(lista);
            return;
        }
        
        for(int i=0;i<inventario.size();i++){
            if(inventario.get(i).getNombre().contains(busquedaModificar.getText())){
                lista.addElement(inventario.get(i).getNombre());
            }
        }
        listaPelis.setModel(lista);
    }//GEN-LAST:event_busquedaModificarKeyReleased

    private void listaPelisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPelisMouseClicked
        // TODO add your handling code here:

        try{
        selected=inventario.get(buscarProducto(listaPelis.getSelectedValue(),inventario));
        } catch (IndexOutOfBoundsException e){
            return;
        }
        
        //Ingresar datos del producto
        nombreModi.setText(selected.getNombre());
        precioModi.setValue(selected.getPrecio());
        cantModi.setValue(selected.getCantidad());
        
        //Activar campos y botones
        nombreModi.setEnabled(true);
        precioModi.setEnabled(true);
        cantModi.setEnabled(true);
        modificar.setEnabled(true);
    }//GEN-LAST:event_listaPelisMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        int index=buscarProducto(selected.getNombre(),inventario);
        Number value = (Number) precioModi.getValue();
        double precio = value.doubleValue();

        // Redondear a dos decimales usando BigDecimal
        BigDecimal bd = new BigDecimal(precio).setScale(2, RoundingMode.HALF_UP);
        
        //Modificar Tabla
        DefaultTableModel inv=(DefaultTableModel)tablaInventario.getModel();
        for(int i=0;i<inv.getRowCount();i++){
            System.out.println("Entro veces "+(i+1));
            if(inv.getValueAt(i, 0).equals(inventario.get(index).getNombre())){
                System.out.println("Si lo encontro");
                inv.setValueAt(nombreModi.getText(), i, 0);
                inv.setValueAt(bd.doubleValue(), i, 1);
                inv.setValueAt(cantModi.getValue(), i, 2);
                break;
            }
        }
        
        //Guardar en inventario
        inventario.get(index).setNombre(nombreModi.getText());
        inventario.get(index).setCantidad((int)cantModi.getValue());
        
        inventario.get(index).setPrecio(bd.doubleValue());
        
        System.out.println(inventario.get(index));
        
        nombreModi.setText("");
        cantModi.setValue(1);
        precioModi.setValue(0);
        
        //Inicializar los componentes
        nombreModi.setEnabled(false);
        precioModi.setEnabled(false);
        cantModi.setEnabled(false);
        modificar.setEnabled(true);
        listaPelis.clearSelection();
        busquedaModificar.setText("");
        listaPelis.removeAll();
    }//GEN-LAST:event_modificarActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        // TODO add your handling code here:
        Producto Int=new Producto();
        Int.setNombre("Intensamente");
        Int.setPrecio(150.50);
        Int.setCantidad(5);
        inventario.add(Int);
        
        Producto Wic=new Producto();
        Wic.setNombre("Wicked");
        Wic.setPrecio(320.15);
        Wic.setCantidad(20);
        inventario.add(Wic);
        
        Producto Ste=new Producto();
        Ste.setNombre("Steven Universe: The Movie");
        Ste.setPrecio(95.75);
        Ste.setCantidad(15);
        inventario.add(Ste);
        
        testButton.setEnabled(false);
        
        iniciarTabla();
    }//GEN-LAST:event_testButtonActionPerformed

    public final void iniciarTabla(){
        DefaultTableModel m=(DefaultTableModel)tablaInventario.getModel();
        Producto objeto;
        for(int i=0;i<inventario.size();i++){
            objeto=inventario.get(i);
            m.addRow(new Object[]{objeto.getNombre(),objeto.getPrecio(),objeto.getCantidad()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField busquedaModificar;
    private javax.swing.JTextField busquedaPrincipal;
    private javax.swing.JLabel cantLabel;
    private javax.swing.JSpinner cantModi;
    private javax.swing.JSpinner cantidadPeli;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminarAux;
    private javax.swing.JLabel eliminarDatos;
    private javax.swing.JTextField eliminarField;
    private javax.swing.JLabel eliminarLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList<String> listaPelis;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nombreModi;
    private javax.swing.JTextField nombrePeli;
    private javax.swing.JFormattedTextField precioModi;
    private javax.swing.JFormattedTextField precioPeli;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton salirInventario;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables
}
